### ISSUE TITLE
Feature: Multiple Listeners (2+ ports bind + with unique motd and other)

### ISSUE THREAD

**Issue by softy-oniguru** [PaperMC/Velocity#1046]
I would like to see this function in Velocity, because after switching from Bungeecord I could not find it. In Bungeecord, this is implemented using:

```
listeners:
    - server1: "address"
    motd: "Welcome to server1"
    ...something...
    
    - server2: "address"
    motd: "Welcome to server2"
    ...something...
```

I think you can also implement this somehow using lists, just specify a separate section in the config named [Network] and make a list of servers and connection data into it (bind, motd, show-max-players, online-mode)

My idea about it in the config:
```
[network]
bind = "localhost:25565"
motd = "<#09add3>A Velocity Server"
show-max-players = 500
#online-mode = true (I think this can be a difficult task, because it is not implemented even in bungeecord)

[network]
bind = "localhost:25566"
motd = "<#d3ad09>A Velocity Server"
show-max-players = 250
#online-mode = false
```

in JSON form it would look like:
```
{
  "network": [
    { "bind": "localhost:25565", "motd": "<#09add3>A Velocity Server", "show-max-players": 250, "online-mode": true},
    { "bind": "localhost:25566", "motd": "<#d3ad09>A Velocity Server", "show-max-players": 500, "online-mode": false}
  ]
}
```

_I don't know English well, I use a translator, so there may be inaccuracies in the translation._
