### ISSUE TITLE
No skins in server

### ISSUE THREAD

**Issue by arnon001** [PaperMC/Velocity#1273]
When I enter the server I don't have skin, the proxy is set to online mode and the paper.yml is also to true
![2024-03-18_13 06 23](https://github.com/PaperMC/Velocity/assets/58848496/8f582df7-0f83-4446-8b12-3003445faae2)
velocity config
```toml
online-mode = true
```

paper config
```yaml
settings:
  baby-zombie-movement-speed: 0.5
  limit-player-interactions: true
  velocity-support:
    enabled: true
    online-mode: true
    secret: secret
```

**Comment by Timongcraft** [comment]
What is your Velocity and Paper version?
What plugins are you using on the proxy and backend?

**Comment by Timongcraft** [comment]
What is this "paper config"?
In the 1.20.4 it should be in "/config/paper-global.yml"
And look like this:
```yml
proxies:
  bungee-cord:
    online-mode: true
  proxy-protocol: false
  velocity:
    enabled: true
    online-mode: true
    secret: <SECRET>
```
