### ISSUE TITLE
Can't join Velocity Server with BungeeGuard (Unable to connect to lobby: Unable to authenticate)

### ISSUE THREAD

**Issue by DavidFrings** [PaperMC/Velocity#1325]
Hi,
I wanted to make a Velocity server with bungeeGuard (paper on the MC server side), but I can't join my server

I set bungeecord in the spigot.yml to true
I also set bungeecord to true in the velocity.toml

the forwarding.secret contains:
````secret
{TOKEN}
````
the config.yml in BungeeGuard contains:
````yml
# BungeeGuard Configuration

# Allowed authentication tokens.
allowed-tokens:
  - "TOKEN"

# Messages

# Kick message sent to connections without any forwarded data from the proxy.
# Most likely a vanilla client connecting directly to the server, bypassing the proxy.
no-data-kick-message: "&cUnable to authenticate - no data was forwarded by the proxy."

# Kick message sent to connections with forwarding data, but without a correct BungeeGuard token
# included in their handshake. Assuming BungeeGuard is installed correctly on all proxies,
# this is most likely a client trying to exploit the BungeeCord protocol to spoof their uuid.
invalid-token-kick-message: "&cUnable to authenticate."
````
TOKEN = my token
