### ISSUE TITLE
Build #396 Breaks forwarding

### ISSUE THREAD

**Issue by p4ncak3s-R0ck** [PaperMC/Velocity#1347]
When attempting to join a server Build 396 I was instantly kick from the server claiming "This server requires you to connect with Velocity." After joining via the proxy.

# Relevant Config
## velocity.toml
```
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"
```
## paper-global.yml
```
  velocity:
    enabled: true
    online-mode: true
    secret: '************'
```

Full Logs:
https://gist.github.com/JaJa99335/5bb56cd39ba48f1d805371417c1744c2
