### ISSUE TITLE
Config version updates breaks forced-hosts section

### ISSUE THREAD

**Issue by valaphee** [PaperMC/Velocity#1405]
### Expected Behavior

When a config version is update the forced-hosts section should stay
```toml
[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
lobby = "127.0.0.1:25578"
#factions = "127.0.0.1:30067"
#minigames = "127.0.0.1:30068"

# In what order we should try servers when a player logs in or is kicked from a server.
try = ["lobby"]

[forced-hosts]
# Configure your forced hosts here.
#"lobby.example.com" = [
#    "lobby"
#]
#"factions.example.com" = [
#    "factions"
#]
#"minigames.example.com" = [
#    "minigames"
#]
```

### Actual Behavior

```toml
forced-hosts = {}

[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	lobby = "127.0.0.1:25578"
	#factions = "127.0.0.1:30067"
	#minigames = "127.0.0.1:30068"
	# In what order we should try servers when a player logs in or is kicked from a server.
	try = ["lobby"]
# Configure your forced hosts here.
#"lobby.example.com" = [
#    "lobby"
#]
#"factions.example.com" = [
#    "factions"
#]
#"minigames.example.com" = [
#    "minigames"
#]
```

### Steps to Reproduce

Having a legacy config (or changing the config version), and starting velocity

### Plugin List

N/A

### Velocity Version

Latest commit
