### ISSUE TITLE
Feature Request: Support WebSocket connect to Velocity

### ISSUE THREAD

**Issue by 8MiYile** [PaperMC/Velocity#1585]
### Requested Feature

I hope to be able to access the Velocity server through the WebSocket protocol from the client
to fix issues with access quality in different regions
```toml
bind = false

[websocket]
enable = true
bind = ["tcp:127.0.0.1:25565", "unix:/tmp/velocity.sock"]
trust-x-forwarded-for = true
# This option is mainly used for Nginx reverse proxy. Do not enable this option if you are not using Nginx or similar services.
http-response = "302|https://example.com"
#http-response = "200|./index.html"
#http-response = "404"
#http-response = "504"
ssl = false
# If you are using Nginx's reverse proxy feature, do not enable SSL.
#only-ssl-connect = true
# If only-ssl-connect is set to true with SSL enabled, the server will only accept WSS protocol requests
#ssl-fullchain-path = "./fullchain.pem"
#ssl-privkey-path = "./privkey.pem"
```

### Why is this needed?

It is useful in special scenarios because this strategy mainly allows for obtaining the client IP at Nginx

### Alternative Solutions

i tried to use [websocat](https://github.com/vi/websocat/releases) converts websocket requests to tcp requests in server-side, but this will cause Velocity to fail to obtain the client IP address 
```mermaid
stateDiagram
  direction LR
  Client --> CDN
  CDN --> Nginx
  Nginx --> WebSocat
  WebSocat --> Velocity
  
  Client:Client
  Client:using websocat

  Nginx:Nginx
  Nginx:listen 443 SSL
  Nginx:proxy_pass 25564

  WebSocat:WebSocat
  WebSocat:listen 25564
  WebSocat:proxy_pass 25565

  Velocity:Velocity
  Velocity:listen 25565
```
