### ISSUE TITLE
Forced hosts are ignored

### ISSUE THREAD

**Issue by Kebab11noel** [PaperMC/Velocity#653]
When connecting to the server, velocity always forwards the connection to the `lobby` server. The config:
```toml
[servers]
  lobby = "172.18.0.1:25565"
  prvt = "172.18.0.1:3540"
  prvt1 = "172.18.0.1:3541"

[forced-hosts]
  "prvt.mc.example.com" = "prvt"
  "medieval.mc.example.com" = "prvt1"
  ```

**Comment by Xernium** [comment]
This usually happens when your forced hosts use SRV records, the target is a CNAME record or you’re using something to mask DNS like Cloudflare.
It may also be a plugin interfering.
It‘s only expected to work correctly, due to how the Minecraft Java client works, if you have an A-Record with a server on port 25565 as the forced host. That said, usually an SRV-Record and an A-Record with the same name should also work correctly most of the time, it‘s really hit-or-miss.

**Comment by Kebab11noel** [comment]
Cloudflare only proxies HTTP traffic, however i use TCPShield. My current DNS setup is:
mc.@ CNAME TCP-SHIELD-DOMAIN
*.mc.@ CNAME mc.@
and an srv on root pointing to mc.@
But i believe this isn't an issue with my DNS config since, i can connect to the server and i wrote a small plugin to monitor vhosts and in the logs i can see the correct name.
<details>
<summary>Test plugin and console log</summary>
Source code:

```java
@Plugin(id = "handshake-monitor", name = "Handshake Monitor", version = "1.0-SNAPSHOT")
public class HandshakeMonitor {
  @Inject
  private Logger logger;
  
  @Subscribe
  public void onProxyInitialization(ProxyInitializeEvent event) {}
  
  @Subscribe
  public void onConnectionHandshake(ConnectionHandshakeEvent event) {
    InboundConnection conn = event.getConnection();
    this.logger.info(conn.getRemoteAddress().toString() + " -> " + conn.getVirtualHost().orElse(null) + " (proto=" + conn
        .getProtocolVersion().getName() + "; isActive=" + conn.isActive() + ")");
  }
}
```

Log entries:

```
[handshake-monitor]: /XXX.XXX.XXX.XXX:46838 -> prvt.mc.example.com/<unresolved>:25565 (proto=1.18; isActive=true)
[connected player] Kebab11noel (XXX.XXX.XXX.XXX/:46838): unable to connect to server lobby
[handshake-monitor]: /XXX.XXX.XXX.XXX:46848 -> medieval.mc.example.com/<unresolved>:25565 (proto=1.18; isActive=true)
[connected player] Kebab11noel (/XXX.XXX.XXX.XXX:46848): unable to connect to server lobby
```
</details>

**Comment by Xernium** [comment]
Please try to reproduce this *without* any velocity plugins. I suspect the tcpshield plugin or another plugin to be at fault here.

**Comment by Kebab11noel** [comment]
I disabled both the tcpshield and handshake-monitor plugin (so every plugin), and the issue persists.

**Comment by Kebab11noel** [comment]
Found the [problematic line](https://github.com/PaperMC/Velocity/blob/596d4758ba9efedc60ede2789644ea10263c48e4/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L727), I believe the issue is that `java.net.InetSocketAddress#getHostString` returns not just the domain but other information too, like `/<unresolved>:25565` or sometimes (maybe depending on the client?) some base64 encoded data, so it will never match with the hosts defined in the config.

I'll do a fix in the following days.

**Comment by Kebab11noel** [comment]
Further investigation shows that this issue is related to TCPShield, looks like TCPShield's plugin couldn't cleanup the server address before the forced host decision is made.

**Comment by electronicboy** [comment]
This was basically resolved down to TCPShield shoving stuff in the hostname for encoding stuff

**Comment by MaxLevs** [comment]
> This usually happens when your forced hosts use SRV records, the target is a CNAME record

I didn't understand what else is it supposed to be?

For example I have SRV record `foo.bar.example.org` that points to `host1.example.org` that is an A record to my pc where I have test mc-server and vilocity running. 
```dig
_minecraft._tcp.foo.bar.example.org. 600 IN SRV 1 0 25565 host1.example.org
host1.example.org.      600     IN      A       <my_ip>
```

Velocity have configuration like follow

```toml
basic = "127.0.0.1:25568" # yes. the test server's port is 25568

# In what order we should try servers when a player logs in or is kicked from a server.
try = [] # I don't need fallback or default server

# Configure your forced hosts here.
[forced-hosts]
"foo.bar.example.org" = [
    "basic"
]
```

And if I open multiplayer's servers list I receive server's logo and MOTD correclty.
But if I try to connect it says that there are no servers to connect to. And if I have a try list it just use it ignoring forced hosts.

Can u explain what it supposed to be if not SRV / CNAME?
