### ISSUE TITLE
Feature request: Unix domain socket binding support

### ISSUE THREAD

**Issue by skbeh** [PaperMC/Velocity#906]
I am wondering why https://github.com/PaperMC/Velocity/pull/422 is not merged in 3.x.x releases.
I think that it would not be a breaking change, and I need this feature.

**Comment by astei** [comment]
Because it _is_ a breaking API change at the moment due to the `VelocityConfiguration` class.

**Comment by skbeh** [comment]
Is it possible to integrate it to the 3.2 release?
Also, is there any plan for releasing new release?

**Comment by astei** [comment]
3.2 doesn't break API. It's not going in there.

Asking when it's going to go into a future release means less time for it to be added.

**Comment by 8MiYile** [comment]
I hope your UNIX Socket method is used for the following configuration
Example:
```toml
[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
lobby01 = "tcp:127.0.0.1:30066"
lobby02 = "unix:/tmp/mcs-lobby.sock"
```
